apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  type: LoadBalancer
  ports:
  - port: 9901
    targetPort: 9901    
    name: admin
  - port: 8080
    targetPort: 8080    
    name: tcp    
  selector:
    app: envoy