apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  selector:
    matchLabels:
      app: envoy
  replicas: 1
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.20-latest
        ports:
        - containerPort: 9901
          name: config
        - containerPort: 8080
          name: test

        volumeMounts:
        - mountPath: /etc/envoy # mount envoy-conf volume to /etc/envoy
          readOnly: true
          name: envoy-conf
      volumes:
      - name: envoy-conf
        configMap:
          name: envoy-conf # place ConfigMap `envoy-conf` on /etc/envoy
          items:
            - key: envoy.yaml
              path: envoy.yaml
      - name: log
        emptyDir: {}
